### ISSUE TITLE
[Feature request]: 更换真链接延迟测试地址

### ISSUE THREAD

**Issue by kaylee595** [lazycat75246/v2rayN-AS2#1]
### 相关问题

感谢lazycat75246, 有的网址google可以访问, 但是一些服务不行, 我想更换真链接测试地址应该怎么做呀

### 描述你希望的解决方案

更换真链接google测试地址.

### 描述你所考虑的替代方案

v2rayN的最新版是有更换真链接测试地址的, 但是没有自动切换节点功能

### 我确认已查询历史issues

- [X] 是

**Comment by lazycat75246** [comment]
1.開啟檔案,安裝目錄\guiConfigs\guiNConfig.json
2.找這個選項 speedPingTestUrl 後面引號裡的網址修改成你需要的
3.重啟v2rayn

**Comment by kaylee595** [comment]
芜湖, 这太完美了, 非常感谢@lazycat75246 的[v2rayN-AS2](https://github.com/lazycat75246/v2rayN-AS2)🤩🤩🤩
