### ISSUE TITLE
[Bug]: 连续运行几天会卡死

### ISSUE THREAD

**Issue by kaylee595** [lazycat75246/v2rayN-AS2#2]
### 预期情况

正常运行

### 实际情况

运行了几天后卡死, 第一次运行了4天卡死, 以为是偶然现象, 第二次运行7天卡死. 不知道和系统有没有关系.

## 系统信息
版本	Windows Server 2022 Datacenter
版本号	21H2
安装日期	‎2024/‎1/‎7
操作系统内部版本	20348.2113

### 复现方法

没有特定的触发周期

### 日志信息

卡死了, 日志滚动在最上方, 看不到最底部的输出.

### 额外信息

使用了自动切换, 始终最低延迟模式.

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues

- [X] 是

**Comment by lazycat75246** [comment]
請嘗試新發布的版本

**Comment by kaylee595** [comment]
> 請嘗試新發布的版本

OK, 大佬出手真迅速, 已经用上V6.33.4

**Comment by kaylee595** [comment]
> 請嘗試新發布的版本

好像出现了更严重的问题, 我的电脑断网了. 我确保我的电脑在没有运行V2ray的情况下, 运行最新版本v6.33.4, 然后我确保系统代理走到127.0.0.1:10809, 但是这时我的电脑无法访问任何网址, 我的代理是正常的, 通过了真连接延迟的测试. 我发现日志输出那里没有打印到我访问的地址.

**Comment by lazycat75246** [comment]
> > 請嘗試新發布的版本
> 
> 好像出现了更严重的问题, 我的电脑断网了. 我确保我的电脑在没有运行V2ray的情况下, 运行最新版本v6.33.4, 然后我确保系统代理走到127.0.0.1:10809, 但是这时我的电脑无法访问任何网址, 我的代理是正常的, 通过了真连接延迟的测试. 我发现日志输出那里没有打印到我访问的地址.

1.建議你用win的"任務管理器"->"詳細資料",看一下是不是有多個v2rayn進程,xray進程(看你用的什麼核心),把這些進程全殺掉,然後再啟動.
2.在關掉自動切換的情況下,手動選擇節點,看訪問是否正常.
3.另外建議你嘗試更新一下xray核心(檢查更新->xray core)
4.請把選擇並應用了節點後,日誌最開始的那幾行(從"啟動服務"到"系統代理設定改變")複製發一下,

**Comment by kaylee595** [comment]
> > > 請嘗試新發布的版本
> > 
> > 
> > 好像出现了更严重的问题, 我的电脑断网了. 我确保我的电脑在没有运行V2ray的情况下, 运行最新版本v6.33.4, 然后我确保系统代理走到127.0.0.1:10809, 但是这时我的电脑无法访问任何网址, 我的代理是正常的, 通过了真连接延迟的测试. 我发现日志输出那里没有打印到我访问的地址.
> 
> 1.建議你用win的"任務管理器"->"詳細資料",看一下是不是有多個v2rayn進程,xray進程(看你用的什麼核心),把這些進程全殺掉,然後再啟動. 2.在關掉自動切換的情況下,手動選擇節點,看訪問是否正常. 3.另外建議你嘗試更新一下xray核心(檢查更新->xray core) 4.請把選擇並應用了節點後,日誌最開始的那幾行(從"啟動服務"到"系統代理設定改變")複製發一下,

```
2024/09/04 23:01:34 系统代理设置改变ForcedChange
初始化配置
启动服务(2024/09/04 23:01:49)...
C:\Users\Administrator\Desktop\application\v2rayN-AS-6.33.4\guiConfigs\configSpeedtest.json
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 windows/amd64)
A unified platform for anti-censorship.
2024/09/04 23:01:49 [Info] infra/conf/serial: Reading config: configSpeedtest.json
2024/09/04 23:01:49 [Warning] core: Xray 1.8.6 started
```

我检查了任务管理器, 确认了在没有运行v2ray的情况下, 启动了新版本, 但是它不能工作. 当我关掉它, 开启旧版本是可以正常工作的, 应该不存在端口被占用的情况

**Comment by kaylee595** [comment]
2. 在关闭了自动切换节点的情况下, 它还是无法正常工作.
 3. 好像更新不动, 一直在0%, 可能它这个更新不能使用翻墙的代理, github访问太慢了
 4. 在旧版本中, 当我选中完一个节点会输出:
```
配置成功
[Shadowsocks] 香港Y02 | IEPL(c8v7i-g03***art:14561)
启动服务(2024/09/04 23:10:26)...
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 windows/amd64)
2024/09/04 23:10:27 Using default config:  C:\Users\Administrator\Desktop\application\v2rayN-autoSwitchNode\guiConfigs\config.json
A unified platform for anti-censorship.
2024/09/04 23:10:27 [Info] infra/conf/serial: Reading config: C:\Users\Administrator\Desktop\application\v2rayN-autoSwitchNode\guiConfigs\config.json
2024/09/04 23:10:27 [Warning] core: Xray 1.8.6 started
2024/09/04 23:10:28 系统代理设置改变ForcedChange
```
但是在新版本中, 我切换节点日志不会输出任何东西, 在我的上一个回复中出现了日志是因为测试了真链接延迟才有出现:
```
初始化配置
启动服务(2024/09/04 23:01:49)...
C:\Users\Administrator\Desktop\application\v2rayN-AS-6.33.4\guiConfigs\configSpeedtest.json
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 windows/amd64)
A unified platform for anti-censorship.
2024/09/04 23:01:49 [Info] infra/conf/serial: Reading config: configSpeedtest.json
2024/09/04 23:01:49 [Warning] core: Xray 1.8.6 started
```
手动切换节点没有任何日志输出

**Comment by lazycat75246** [comment]
啟用下面設定可以解決問題
設定->v2rayn設定->啟用統計 打開這個開關

**Comment by kaylee595** [comment]
> 啟用下面設定可以解決問題 設定->v2rayn設定->啟用統計 打開這個開關

在我打开了"启用统计"设定之后, 出现日志了, 它告诉我需要在"bin/sign_box"下安装sing-box.exe, 我安装完之后它就可以正常工作了.
感谢 @lazycat75246 , 让我试运行几天看看会不会卡死.

**Comment by kaylee595** [comment]
有点奇怪, 几天时间后, v2rayN这个主进程占用219M, 是有内存泄漏的可能吗, 我服务器的系统内存只有2G, 加上一些其他的服务的话不太够了, 一致报警内存不够. 从9月6号开始才有的一直报警. 我好像是在9月5号开始更换的软件. 也就说以前软件内存是比较低的? 这个能优化吗, 我的系统内存不够太多天, 一直没上去, 今天系统卡死了, 上去看了windows日志才发现🤔

**Comment by lazycat75246** [comment]
> 有点奇怪, 几天时间后, v2rayN这个主进程占用219M, 是有内存泄漏的可能吗, 我服务器的系统内存只有2G, 加上一些其他的服务的话不太够了, 一致报警内存不够. 从9月6号开始才有的一直报警. 我好像是在9月5号开始更换的软件. 也就说以前软件内存是比较低的? 这个能优化吗, 我的系统内存不够太多天, 一直没上去, 今天系统卡死了, 上去看了windows日志才发现🤔

1.請嘗試最新的版​​本
2.請嘗試關閉統計功能 "參數設定-v2rayn設定->啟用統計" 關閉這裡 有可能會減少記憶體佔用

**Comment by kaylee595** [comment]
> > 有点奇怪, 几天时间后, v2rayN这个主进程占用219M, 是有内存泄漏的可能吗, 我服务器的系统内存只有2G, 加上一些其他的服务的话不太够了, 一致报警内存不够. 从9月6号开始才有的一直报警. 我好像是在9月5号开始更换的软件. 也就说以前软件内存是比较低的? 这个能优化吗, 我的系统内存不够太多天, 一直没上去, 今天系统卡死了, 上去看了windows日志才发现🤔
> 
> 1.請嘗試最新的版​​本 2.請嘗試關閉統計功能 "參數設定-v2rayn設定->啟用統計" 關閉這裡 有可能會減少記憶體佔用

OK, 非常感谢大佬, 已经使用v6.33.6. 我猜测可能是我开启了"启用统计", 因为我之前好像没打开这个.
