### ISSUE TITLE
[Feature request]: 支持在更新订阅时给新内容自动勾选切换

### ISSUE THREAD

**Issue by hmjz100** [lazycat75246/v2rayN-AS2#3]
### 相关问题

软件在更新订阅后，不能自动添加新内容的“自动”勾选框

### 描述你希望的解决方案

给订阅界面设置一个开关来决定是否自动勾选，勾选后会给该订阅更新的内容添加“自动”勾选框

### 描述你所考虑的替代方案

无

### 我确认已查询历史issues

- [X] 是

**Comment by lazycat75246** [comment]
謝謝你的建議,可能會在下個功能更新版本增加該功能

**Comment by hmjz100** [comment]
还有一个不知道是 Bug 还是什么东西的问题，在订阅更新后如果是相同内容似乎会出现重复的内容：
![image](https://github.com/user-attachments/assets/96663304-8191-4a5d-8200-a36fc15c2b9c)

**Comment by lazycat75246** [comment]
最新的v6.33.7版本已發佈,你需求的功能已添加,此功能僅在訂閱更新時觸發,具體使用方法如下:
1.在新增或編輯訂閱的頁面新增更新訂閱後按關鍵字將節點加入自動切換.
支援的格式:
1.空白(什麼都不填),表示不自動加入到自動切換
2. all 代表新增所有節點到自動切換(會自動過濾無效節點)
3.關鍵字以垂直線隔開 例如 香港|台灣表示所有香港和台灣節點都加入自動切換
![7-1](https://github.com/user-attachments/assets/0cf2b238-cd7d-4d8a-b404-b063a48a95e3)

你上面提到的那個bug,已經做了程式碼優化,可能已經解決,請在使用中再回饋

**Comment by hmjz100** [comment]
感谢您的更新，还有一个小Bug，就是下图这里“订阅分组设置”界面最下方有文本重叠了，不过不影响使用
![image](https://github.com/user-attachments/assets/b8ae4149-5b6c-4be5-b8b6-3b43561ae645)

**Comment by hmjz100** [comment]
刚刚又试了下新版本，列表的数据还是会有重复，右键列表->移除重复的服务器 后显示数量为 25->25，可是列表却显示有30个服务器项目

**Comment by lazycat75246** [comment]
> 刚刚又试了下新版本，列表的数据还是会有重复，右键列表->移除重复的服务器 后显示数量为 25->25，可是列表却显示有30个服务器项目

在最近的測試中暫未遇到重複的情況,從以前的測試情況看,重複的現像只是界面顯示錯誤,數據庫是正確的,不影響正常運行,最近的修改是更新訂閱前會暫停自動切換,更新完畢後再重新啟動自動切換,這也就是說不是自動切換代碼和訂閱更新的衝突,具體原因暫時沒有找到.

**Comment by lazycat75246** [comment]
> 刚刚又试了下新版本，列表的数据还是会有重复，右键列表->移除重复的服务器 后显示数量为 25->25，可是列表却显示有30个服务器项目

新版本 v6.33.7.1 已更新,對於你提及的bug做了一定優化, 沒有發布新的release,只是替換了v6.33.7

**Comment by hmjz100** [comment]
嗯，新版本重复的数量比之前好很多了，可惜还是有。  
复现：全选 删除 更新订阅 全选 测试真连接 去除重复的服务器 活动服务器就会变成两个  
不过不怎么影响使用，先在此关闭 issues 了

**Comment by lazycat75246** [comment]
新版本 v6.33.7.2 已更新,節點顯示重複的bug應該已經修復
